### ISSUE TITLE
Erreur a l'installation

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/dseshiny#1]
Bonjour,

A l'installation avec le code de la page "readme" , j'ai l'erreur 
``` 
Failed to install 'unknown package' from GitLab:
  impossible d'ouvrir l'URL 'https://gitlab-forge.din.developpement-durable.gouv.fr/api/v4/projects/olivier.chantrel%2Fdseshiny/repository/files/DESCRIPTION/raw?ref=HEAD' 
```

Si je telecharge le zip et que je le modifie pour l'installer. J'ai dézipper le fichier telechargé, j'ai ensuite été dans les sous dossier jusqu'a trouver le dossier a zipper (le dernier dosssier avant d'avoir description et proj). Il semble installer, mais après il ne trouve pas :( 

``` 
Installing package into ‘C:/Users/marlyse.clement/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified) 
```

``` 
Error in library(dseshiny) : 
  ‘dseshiny’ n'est pas un nom correct de package installé 
```

**Comment by virgilecs** [comment]
Bonjour Marlyse,

ça devrait fonctionner comme ceci
remotes::install_github("MTES-MCT/dseshiny/dseshiny")

Virgile
